method: psgn
data:
  input_type: pointcloud
  path: data/ShapeNet
  pointcloud_n: 300
  pointcloud_noise: 0.005
  pointcloud_target_n: 1024
model:
  decoder: simple
  encoder: pointnet_resnet 
  encoder_kwargs:
    hidden_dim: 512 
  c_dim: 512 
  z_dim: 0
training:
  out_dir:  out/pointcloud/psgn
  batch_size: 64
  model_selection_metric: chamfer
test:
  eval_mesh: false
  eval_pointcloud: true
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  generate_mesh: false
