method: r2n2
data:
  input_type: pointcloud
  path: data/ShapeNet
  pointcloud_n: 300
  pointcloud_noise: 0.005
model:
  decoder: simple
  encoder: pointnet_resnet
  encoder_kwargs:
    hidden_dim: 512 
  c_dim: 512 
  z_dim: 0
training:
  out_dir:  out/pointcloud/r2n2
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
test:
  threshold: 0.4
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
